/* This file was last modified by Zain B */

package com.zbt;

//Stub, look in winbt
public enum NetworkingRequest {
    REQUEST_PAIRED_DEVICES,
    CANCEL_PAIRED_DEVICE_SEARCH,

    REQUEST_BLUETOOTH_SOCKET_CONNECTION,
    REQUEST_BLUETOOTH_SERVER_SOCKET_CONNECTION,

    // REQUEST_BLUETOOTH_ADAPTER_NAME,
    // REQUEST_BLUETOOTH_ADAPTER_ADDRESS,
    // REQUEST_BLUETOOTH_ADAPTER_UUIDS,
    // REQUEST_BLUETOOTH_ADAPTER_CLASS_OF_DEVICE,
    // REQUEST_BLUETOOTH_ADAPTER_TYPE_OF_DEVICE,

    REQUEST_BLUETOOTH_DEVICE_SERVICE_UUID,
    REQUEST_BLUETOOTH_DEVICE_ALL_BASIC_UUIDS,

    REQUEST_BLUETOOTH_L2CAP_CONNECTION,
    REQUEST_BLUETOOTH_L2CAP_SEND,
    REQUEST_BLUETOOTH_L2CAP_READ,
    REQUEST_BLUETOOTH_L2CAP_MAXTU,
    REQUEST_BLUETOOTH_HID_CONNECTION
}
